name: "xtreamly-lit-website"

services:
  dashboard_server:
    build: .
    container_name: xtreamly_lit_website
    command: ["node", "-r", "dotenv/config", "build"]
    network_mode: host
    ports:
      - "4001:4001"
    environment:
      HOST: 127.0.0.1
      PORT: 4001
      HOST_HEADER: X-Forwarded-Host
      PROTOCOL_HEADER: X-Forwarded-Proto
      ADDRESS_HEADER: X-Real-IP

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx_dashboard_reverse_proxy
  #   network_mode: host
  #   ports:
  #     - 5001:5001
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - /etc/letsencrypt/live/app.defisocket.com/fullchain.pem:/etc/ssl/certificate.pem
  #     - /etc/letsencrypt/live/app.defisocket.com/privkey.pem:/etc/ssl/private_key.pem
